version: '3'
services:
  postgres:
    image: containerregistryiuliuandreisteau30642.azurecr.io/db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ds
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  backend:
    image: containerregistryiuliuandreisteau30642.azurecr.io/iuliuandreisteau30642backend:90
    restart: always
    environment:
      DB_IP: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: ds
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: containerregistryiuliuandreisteau30642.azurecr.io/iuliuandreisteau30642frontend:86
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - backend

